baseURL = "https://kyriezheng.github.io/"
languageCode = "en-us"
title = "KyrieZheng's Blog"
theme = "hugo-PaperMod"
publishDir = "docs"
paginate = 4
# searchHidden = true
ShowToc = true

[taxonmies]
    tag = "tags"

[menu]
    [[menu.main]]
        name = "archives"
        weight = 2
        url = "/archives"
    [[menu.main]]
        name = "post"
        weight = 1
        url = "/posts"
    [[menu.main]]
        name = "about me"
        weight = 3
        url = "/about"

[params]
  # Site author
  author = "KyrieZheng"

  # homepage é¡µæè¿°ä¿¡æ¯
  description = "æˆ‘çš„åšå®¢ç«™ç‚¹"
  ShowPostNavLinks = true
  ShowBreadCrumbs = true

[[params.socialIcons]]
    name = "github"
    url = "https://github.com/KyrieZheng"

[params.utteranc]         # utteranc is a comment system based on GitHub issues. see https://utteranc.es
    enable = true
    repo = "KyrieZheng/KyrieZheng.github.io"    # The repo to store comments
    issueTerm = "pathname"


[params.homeInfoParams]
    Title = "Hi there ğŸ‘‹"
    Content = "Many a mickle makes a muckle"
